description: |
  Provisions and deploys My Shuttle to a web app (with a mysql db)
  Runs integration tests

inputs:
  dbServerName:
    description: mysql servername
    required: true
  dbUser:
    description: mysql username
    required: true
  dbPassword:
    description: mysql password
    required: true
  ResourceGroupName:
    description: Resource group name
    required: true
  artifactsName:
    description: artifacts name
    required: true
  SiteName:
    description: WebApp name
    required: true
  client-id:
    required: true
    description: azure tenant id
  tenant-id:
    required: true
    description: azure tenant id
  subscription-id:
    required: true
    description: azure subscription id

outputs:
  webapp-url:
    description: Deployed web app url
    value: ${{ steps.deployWebApp.outputs.webapp-url }}

runs:
  using: "composite"
  steps:
  - name: Download Build Artifact
    uses: actions/download-artifact@v3.0.2
    with:
      path: artifacts
      name: ${{ inputs.artifactsName }}

  - uses: azure/login@v1
    with:
      client-id: ${{ inputs.client-id }}
      tenant-id: ${{ inputs.tenant-id }}
      subscription-id: ${{ inputs.subscription-id }}

  - name: Create Resource Group ${{ inputs.ResourceGroupName }} if not exists
    uses: Azure/cli@v1.0.8
    with:
      inlineScript: |
          if [ "$(az group exists --name ${{ inputs.ResourceGroupName }})" = "false" ]; then
            echo creating ${{ inputs.ResourceGroupName }} resource group
            az group create --location "eastus2" --name ${{ inputs.ResourceGroupName }} --tags demo=true "ghrepo=${{ github.repository }}"
          fi
  - name: Provision Infra using ARM Template
    uses: Azure/arm-deploy@main
    id: deployARM
    with:
      scope: resourcegroup
      subscriptionId: ${{ inputs.subscription-id }}
      resourceGroupName: ${{ inputs.ResourceGroupName }}
      template: ${{ inputs.artifactsName }}/IaC/azuredeploy.json
      deploymentMode: Incremental
      parameters: siteName="${{ inputs.SiteName }}" administratorLogin="${{ inputs.dbUser }}" administratorLoginPassword="${{ inputs.dbPassword }}" dbServerName="${{ inputs.dbServerName }}"

  - name: Azure MYSQL Deploy
    uses: Azure/mysql@v1
    with:
      server-name: ${{ steps.deployARM.outputs.databaseServer }}
      username: ${{ inputs.dbUser }}@${{ steps.deployARM.outputs.databaseServer }}
      password: ${{ inputs.dbPassword }}
      sql-file: ${{ inputs.artifactsName }}/CreateMYSQLDB.sql

  - name: Deploy Web App
    uses: Azure/webapps-deploy@v2
    id: deployWebApp
    with:
      app-name: ${{ inputs.SiteName }}
      package: ${{ inputs.artifactsName }}/target/*.war

  ## Integration tests
  - uses: actions/setup-node@v4
    with:
      node-version: 14

  - name: install playwright
    shell: bash
    run: |
      npx playwright install-deps

  - name: install playwright dependencies
    shell: bash
    run: npm ci
    working-directory: ${{ env.integration_tests_path}}

  - name: run integration tests
    shell: bash
    id: integrationtests
    run: |
      # Workaround to force publishing of results even if tests fail
      # We will fail the workflow later based on testsResult
      npm run test || result=$? || 0
      echo "Test Result [$result]"
      echo "::set-output name=testsResult::$result"
    working-directory: ${{ env.integration_tests_path}}

    env:
      BASE_URL: ${{ steps.deployWebApp.outputs.webapp-url }}/myshuttledev

  - name: Publish Integration Test Results
    uses: EnricoMi/publish-unit-test-result-action@v2
    with:
      files: '${{ env.integration_tests_path}}/reports/**/junit.xml'
      check_name: Integration Tests ${{ github.job }}

  - name: Upload Build Artifact
    uses: actions/upload-artifact@v3
    with:
      path: ${{ env.integration_tests_path}}/screenshots/**
      name: screenshots-${{ github.job }}

  - name: ZAP Scan
    uses: zaproxy/action-baseline@1e1871e84428617b969d4a1f981a8255630d54b0 # v0.10.0
    with:
      target: '${{ steps.deployWebApp.outputs.webapp-url }}/myshuttledev'
      allow_issue_writing: false

  - name: Create sarif file from zaproxy results
    uses: SvanBoxel/zaproxy-to-ghas@main

  - name: Upload zap scan results
    uses: github/codeql-action/upload-sarif@v3
    with:
      sarif_file: results.sarif

  # Fail workflow if tests have failed
  - name: fail workflow if tests failed
    shell: bash
    run: |
      if [ '${{ steps.integrationtests.outputs.testsResult }}' != '' ] && [ '${{ steps.integrationtests.outputs.testsResult }}' != '0' ]; then
        echo Failed tests
        exit 1
      fi
