name: Delete old workflow runs

permissions:
  actions: write
  
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: 90
      mininum_runs:
        description: 'minimum runs to keep'
        required: true
        default: 6

        
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs:  ${{ github.event.inputs.mininum_runs }}
